name: WheatArmor
version: '1.0-SNAPSHOT'
main: ar1hurgit.wheatarmor.WheatArmor
api-version: '1.21'
commands:
  wheatarmor:
    description: Open Wheat Armor shop
    usage: /wheatarmor
  wheatarmoradmin:
    description: Admin Wheat Armor shop
    usage: /wheatarmor admin

  woodarmor:
    description: Open Wood Armor shop
    usage: /woodarmor
  woodarmoradmin:
    description: Admin Wood Armor shop
    usage: /woodarmor admin

  cavearmor:
    description: Open Cave Armor shop
    usage: /cavearmor
  cavearmoradmin:
    description: Admin Cave Armor shop
    usage: /cavearmor admin

  wheatarmoradmingive:
    description: Give armor to a player
    usage: /wheatarmor admin give <player> <armor>
  woodarmoradmingive:
    description: Give armor to a player
    usage: /woodarmor admin give <player> <armor>
  cavearmoradmingive:
    description: Give armor to a player
    usage: /cavearmor admin give <player> <armor>

permissions:
  wheatarmor.admin:
    description: Allows admin access to WheatArmor
    default: op
