name: WheatArmor
version: '1.0-SNAPSHOT'
main: ar1hurgit.wheatarmor.WheatArmor
api-version: '1.21'
commands:
  wheatarmor:
    description: Open the Wheat Armor shop
    usage: /wheatarmor
    permission: wheatarmor.use
  wheatarmoradmin:
    description: Admin Wheat Armor shop
    usage: /wheatarmor admin
  woodarmor:
    description: Open the Wood Armor shop
    usage: /woodarmor
    permission: wheatarmor.use
  woodarmoradmin:
    description: Admin Wood Armor shop
    usage: /woodarmor admin
  cavearmor:
    description: Open the Cave Armor shop
    usage: /cavearmor
    permission: wheatarmor.use
  cavearmoradmin:
    description: Admin Cave Armor shop
    usage: /cavearmor admin
  richearmor:
    description: Open the Rich Armor shop
    usage: /richearmor
    permission: wheatarmor.use
  sagearmor:
    description: Open the Sage Armor shop
    usage: /sagearmor
    permission: wheatarmor.use

  wheatarmoradmingive:
    description: Give armor to a player
    usage: /wheatarmor admin give <player> <armor>
  woodarmoradmingive:
    description: Give armor to a player
    usage: /woodarmor admin give <player> <armor>
  cavearmoradmingive:
    description: Give armor to a player
    usage: /cavearmor admin give <player> <armor>

permissions:
  wheatarmor.admin:
    description: Allows admin access to WheatArmor
    default: op
